from utils.summarize_chain import SummarizeChain
from utils.prompts import Prompt
from langchain import OpenAI
from langchain.prompts import PromptTemplate
from langchain.chains import LLMChain
from utils.speech import text_to_speech


# """
response = {"chunks": ["\nOnce upon a time, in a faraway land called France, there lived a brave people who were tired of the unfair rule of the monarchy. The people were suffering from the financial crisis caused by the extravagant spending of the monarchy and the unregulated system of taxation. The people were also divided into three distinct estates: the clergy, the nobility, and the common people. The common people were bearing the brunt of taxation and social inequities, while the nobility and the clergy enjoyed exemptions. \n\nAt the same time, the ideas of the Enlightenment were spreading throughout the country, with philosophers such as Rousseau, Voltaire, and Montesquieu advocating for individual rights, equality, and democratic governance. The successful American Revolution further inspired the people of France to stand up against the monarchy. \n\nIn 1789, the financial crisis led to the summoning of the Estates-General, but when the Third Estate's demand for fair representation was rejected, they declared themselves the National Assembly. This marked a significant assertion of popular sovereignty. The storming of the Bastille on July 14, 1789, triggered by the dismissal of popular minister Jacques Necker, is generally seen as the Revolution's actual beginning. This event symbolized the public's defiance against royal authority.", "\nThe legacy of the French Revolution continues to this day. Its ideals of liberty, equality, and fraternity have been adopted by many countries around the world, and its principles of democracy and human rights have been enshrined in international law. The Revolution also had a profound impact on the development of modern economics, with its emphasis on the rights of the individual and the importance of free markets. Its legacy is also seen in the rise of nationalism and the spread of revolutionary ideas across the globe. \n\nThe French Revolution was a pivotal moment in world history, and its effects are still felt today. Its legacy of democracy, human rights, and economic freedom has shaped the modern world, and its ideals continue to inspire people around the world.",
                       "\nThe French Revolution has left an indelible mark on the world, and its legacy continues to be felt in many aspects of modern life. Its ideals of liberty, equality, and fraternity have been embraced by many countries, and its principles of democracy and human rights have been enshrined in international law. Its impact on economics has been profound, with its emphasis on the rights of the individual and the importance of free markets. Its legacy is also seen in the rise of nationalism and the spread of revolutionary ideas across the globe. \n\nThe French Revolution serves as a reminder of the power of the people to effect change, and its lessons are still relevant today. Its legacy of democracy, human rights, and economic freedom has shaped the modern world, and its ideals continue to inspire people around the world. Its study is essential to understanding the complexities of revolutionary movements and democratic governance, and its warnings of unchecked power and the potential for violence in radical movements remain as relevant as ever."], "summary": "\nThe French Revolution has left an indelible mark on the world, and its legacy continues to be felt\nin many aspects of modern life. Its ideals of liberty, equality, and fraternity have been embraced\nby many countries, and its principles of democracy and human rights have been enshrined in\ninternational law. Its impact on economics has been profound, with its emphasis on the rights of the\nindividual and the importance of free markets. Its legacy is also seen in the rise of nationalism\nand the spread of revolutionary ideas across the globe. \n\nThe French Revolution serves as a reminder\nof the power of the people to effect change, and its lessons are still relevant today. Its legacy of\ndemocracy, human rights, and economic freedom has shaped the modern world, and its ideals continue\nto inspire people around the world. Its study is essential to understanding the complexities of\nrevolutionary movements and democratic governance, and its warnings of unchecked power and the\npotential for violence in radical movements remain as relevant as ever."}
# """

llm = OpenAI(max_tokens=1000, temperature=0)


def generate_content():
    # chain = SummarizeChain(
    #     source_path=r"C:\Users\jayan\Desktop\Jayanth\Coding\GenAI Hackathon\server\history.pdf")
    # response = chain.get_summary_based_on_prompt()
    story = ''.join(response['chunks'])
    t_to_s_resp = text_to_speech(story)
    return t_to_s_resp
